# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/RTT_MLSSA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/RTT_MLSSA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/RTT_MLSSA/CMakeFiles /cygdrive/c/RTT_MLSSA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/RTT_MLSSA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rttmlssa

# Build rule for target.
rttmlssa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rttmlssa
.PHONY : rttmlssa

# fast build rule for target.
rttmlssa/fast:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/build
.PHONY : rttmlssa/fast

EasyBMP_1.06/EasyBMP_BMP.o: EasyBMP_1.06/EasyBMP_BMP.cpp.o

.PHONY : EasyBMP_1.06/EasyBMP_BMP.o

# target to build an object file
EasyBMP_1.06/EasyBMP_BMP.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/EasyBMP_1.06/EasyBMP_BMP.cpp.o
.PHONY : EasyBMP_1.06/EasyBMP_BMP.cpp.o

EasyBMP_1.06/EasyBMP_BMP.i: EasyBMP_1.06/EasyBMP_BMP.cpp.i

.PHONY : EasyBMP_1.06/EasyBMP_BMP.i

# target to preprocess a source file
EasyBMP_1.06/EasyBMP_BMP.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/EasyBMP_1.06/EasyBMP_BMP.cpp.i
.PHONY : EasyBMP_1.06/EasyBMP_BMP.cpp.i

EasyBMP_1.06/EasyBMP_BMP.s: EasyBMP_1.06/EasyBMP_BMP.cpp.s

.PHONY : EasyBMP_1.06/EasyBMP_BMP.s

# target to generate assembly for a file
EasyBMP_1.06/EasyBMP_BMP.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/EasyBMP_1.06/EasyBMP_BMP.cpp.s
.PHONY : EasyBMP_1.06/EasyBMP_BMP.cpp.s

GBAtext.o: GBAtext.cpp.o

.PHONY : GBAtext.o

# target to build an object file
GBAtext.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/GBAtext.cpp.o
.PHONY : GBAtext.cpp.o

GBAtext.i: GBAtext.cpp.i

.PHONY : GBAtext.i

# target to preprocess a source file
GBAtext.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/GBAtext.cpp.i
.PHONY : GBAtext.cpp.i

GBAtext.s: GBAtext.cpp.s

.PHONY : GBAtext.s

# target to generate assembly for a file
GBAtext.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/GBAtext.cpp.s
.PHONY : GBAtext.cpp.s

OS_interface.o: OS_interface.cpp.o

.PHONY : OS_interface.o

# target to build an object file
OS_interface.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/OS_interface.cpp.o
.PHONY : OS_interface.cpp.o

OS_interface.i: OS_interface.cpp.i

.PHONY : OS_interface.i

# target to preprocess a source file
OS_interface.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/OS_interface.cpp.i
.PHONY : OS_interface.cpp.i

OS_interface.s: OS_interface.cpp.s

.PHONY : OS_interface.s

# target to generate assembly for a file
OS_interface.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/OS_interface.cpp.s
.PHONY : OS_interface.cpp.s

RTTGDIXCB.o: RTTGDIXCB.cpp.o

.PHONY : RTTGDIXCB.o

# target to build an object file
RTTGDIXCB.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTTGDIXCB.cpp.o
.PHONY : RTTGDIXCB.cpp.o

RTTGDIXCB.i: RTTGDIXCB.cpp.i

.PHONY : RTTGDIXCB.i

# target to preprocess a source file
RTTGDIXCB.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTTGDIXCB.cpp.i
.PHONY : RTTGDIXCB.cpp.i

RTTGDIXCB.s: RTTGDIXCB.cpp.s

.PHONY : RTTGDIXCB.s

# target to generate assembly for a file
RTTGDIXCB.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTTGDIXCB.cpp.s
.PHONY : RTTGDIXCB.cpp.s

RTT_2.o: RTT_2.cpp.o

.PHONY : RTT_2.o

# target to build an object file
RTT_2.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_2.cpp.o
.PHONY : RTT_2.cpp.o

RTT_2.i: RTT_2.cpp.i

.PHONY : RTT_2.i

# target to preprocess a source file
RTT_2.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_2.cpp.i
.PHONY : RTT_2.cpp.i

RTT_2.s: RTT_2.cpp.s

.PHONY : RTT_2.s

# target to generate assembly for a file
RTT_2.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_2.cpp.s
.PHONY : RTT_2.cpp.s

RTT_button.o: RTT_button.cpp.o

.PHONY : RTT_button.o

# target to build an object file
RTT_button.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_button.cpp.o
.PHONY : RTT_button.cpp.o

RTT_button.i: RTT_button.cpp.i

.PHONY : RTT_button.i

# target to preprocess a source file
RTT_button.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_button.cpp.i
.PHONY : RTT_button.cpp.i

RTT_button.s: RTT_button.cpp.s

.PHONY : RTT_button.s

# target to generate assembly for a file
RTT_button.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_button.cpp.s
.PHONY : RTT_button.cpp.s

RTT_colours.o: RTT_colours.cpp.o

.PHONY : RTT_colours.o

# target to build an object file
RTT_colours.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_colours.cpp.o
.PHONY : RTT_colours.cpp.o

RTT_colours.i: RTT_colours.cpp.i

.PHONY : RTT_colours.i

# target to preprocess a source file
RTT_colours.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_colours.cpp.i
.PHONY : RTT_colours.cpp.i

RTT_colours.s: RTT_colours.cpp.s

.PHONY : RTT_colours.s

# target to generate assembly for a file
RTT_colours.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_colours.cpp.s
.PHONY : RTT_colours.cpp.s

RTT_generic_decoder.o: RTT_generic_decoder.cpp.o

.PHONY : RTT_generic_decoder.o

# target to build an object file
RTT_generic_decoder.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_generic_decoder.cpp.o
.PHONY : RTT_generic_decoder.cpp.o

RTT_generic_decoder.i: RTT_generic_decoder.cpp.i

.PHONY : RTT_generic_decoder.i

# target to preprocess a source file
RTT_generic_decoder.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_generic_decoder.cpp.i
.PHONY : RTT_generic_decoder.cpp.i

RTT_generic_decoder.s: RTT_generic_decoder.cpp.s

.PHONY : RTT_generic_decoder.s

# target to generate assembly for a file
RTT_generic_decoder.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_generic_decoder.cpp.s
.PHONY : RTT_generic_decoder.cpp.s

RTT_keysyms.o: RTT_keysyms.cpp.o

.PHONY : RTT_keysyms.o

# target to build an object file
RTT_keysyms.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_keysyms.cpp.o
.PHONY : RTT_keysyms.cpp.o

RTT_keysyms.i: RTT_keysyms.cpp.i

.PHONY : RTT_keysyms.i

# target to preprocess a source file
RTT_keysyms.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_keysyms.cpp.i
.PHONY : RTT_keysyms.cpp.i

RTT_keysyms.s: RTT_keysyms.cpp.s

.PHONY : RTT_keysyms.s

# target to generate assembly for a file
RTT_keysyms.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_keysyms.cpp.s
.PHONY : RTT_keysyms.cpp.s

RTT_pane.o: RTT_pane.cpp.o

.PHONY : RTT_pane.o

# target to build an object file
RTT_pane.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_pane.cpp.o
.PHONY : RTT_pane.cpp.o

RTT_pane.i: RTT_pane.cpp.i

.PHONY : RTT_pane.i

# target to preprocess a source file
RTT_pane.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_pane.cpp.i
.PHONY : RTT_pane.cpp.i

RTT_pane.s: RTT_pane.cpp.s

.PHONY : RTT_pane.s

# target to generate assembly for a file
RTT_pane.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_pane.cpp.s
.PHONY : RTT_pane.cpp.s

RTT_patest_wire.o: RTT_patest_wire.cpp.o

.PHONY : RTT_patest_wire.o

# target to build an object file
RTT_patest_wire.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_patest_wire.cpp.o
.PHONY : RTT_patest_wire.cpp.o

RTT_patest_wire.i: RTT_patest_wire.cpp.i

.PHONY : RTT_patest_wire.i

# target to preprocess a source file
RTT_patest_wire.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_patest_wire.cpp.i
.PHONY : RTT_patest_wire.cpp.i

RTT_patest_wire.s: RTT_patest_wire.cpp.s

.PHONY : RTT_patest_wire.s

# target to generate assembly for a file
RTT_patest_wire.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_patest_wire.cpp.s
.PHONY : RTT_patest_wire.cpp.s

RTT_player.o: RTT_player.cpp.o

.PHONY : RTT_player.o

# target to build an object file
RTT_player.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_player.cpp.o
.PHONY : RTT_player.cpp.o

RTT_player.i: RTT_player.cpp.i

.PHONY : RTT_player.i

# target to preprocess a source file
RTT_player.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_player.cpp.i
.PHONY : RTT_player.cpp.i

RTT_player.s: RTT_player.cpp.s

.PHONY : RTT_player.s

# target to generate assembly for a file
RTT_player.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_player.cpp.s
.PHONY : RTT_player.cpp.s

RTT_text_edit_box.o: RTT_text_edit_box.cpp.o

.PHONY : RTT_text_edit_box.o

# target to build an object file
RTT_text_edit_box.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_text_edit_box.cpp.o
.PHONY : RTT_text_edit_box.cpp.o

RTT_text_edit_box.i: RTT_text_edit_box.cpp.i

.PHONY : RTT_text_edit_box.i

# target to preprocess a source file
RTT_text_edit_box.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_text_edit_box.cpp.i
.PHONY : RTT_text_edit_box.cpp.i

RTT_text_edit_box.s: RTT_text_edit_box.cpp.s

.PHONY : RTT_text_edit_box.s

# target to generate assembly for a file
RTT_text_edit_box.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_text_edit_box.cpp.s
.PHONY : RTT_text_edit_box.cpp.s

RTT_vector.o: RTT_vector.cpp.o

.PHONY : RTT_vector.o

# target to build an object file
RTT_vector.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_vector.cpp.o
.PHONY : RTT_vector.cpp.o

RTT_vector.i: RTT_vector.cpp.i

.PHONY : RTT_vector.i

# target to preprocess a source file
RTT_vector.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_vector.cpp.i
.PHONY : RTT_vector.cpp.i

RTT_vector.s: RTT_vector.cpp.s

.PHONY : RTT_vector.s

# target to generate assembly for a file
RTT_vector.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_vector.cpp.s
.PHONY : RTT_vector.cpp.s

RTT_wavpack_decoder.o: RTT_wavpack_decoder.cpp.o

.PHONY : RTT_wavpack_decoder.o

# target to build an object file
RTT_wavpack_decoder.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_wavpack_decoder.cpp.o
.PHONY : RTT_wavpack_decoder.cpp.o

RTT_wavpack_decoder.i: RTT_wavpack_decoder.cpp.i

.PHONY : RTT_wavpack_decoder.i

# target to preprocess a source file
RTT_wavpack_decoder.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_wavpack_decoder.cpp.i
.PHONY : RTT_wavpack_decoder.cpp.i

RTT_wavpack_decoder.s: RTT_wavpack_decoder.cpp.s

.PHONY : RTT_wavpack_decoder.s

# target to generate assembly for a file
RTT_wavpack_decoder.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_wavpack_decoder.cpp.s
.PHONY : RTT_wavpack_decoder.cpp.s

RTT_window.o: RTT_window.cpp.o

.PHONY : RTT_window.o

# target to build an object file
RTT_window.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_window.cpp.o
.PHONY : RTT_window.cpp.o

RTT_window.i: RTT_window.cpp.i

.PHONY : RTT_window.i

# target to preprocess a source file
RTT_window.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_window.cpp.i
.PHONY : RTT_window.cpp.i

RTT_window.s: RTT_window.cpp.s

.PHONY : RTT_window.s

# target to generate assembly for a file
RTT_window.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/RTT_window.cpp.s
.PHONY : RTT_window.cpp.s

compressher_limither.o: compressher_limither.cpp.o

.PHONY : compressher_limither.o

# target to build an object file
compressher_limither.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/compressher_limither.cpp.o
.PHONY : compressher_limither.cpp.o

compressher_limither.i: compressher_limither.cpp.i

.PHONY : compressher_limither.i

# target to preprocess a source file
compressher_limither.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/compressher_limither.cpp.i
.PHONY : compressher_limither.cpp.i

compressher_limither.s: compressher_limither.cpp.s

.PHONY : compressher_limither.s

# target to generate assembly for a file
compressher_limither.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/compressher_limither.cpp.s
.PHONY : compressher_limither.cpp.s

doit_all.o: doit_all.cpp.o

.PHONY : doit_all.o

# target to build an object file
doit_all.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/doit_all.cpp.o
.PHONY : doit_all.cpp.o

doit_all.i: doit_all.cpp.i

.PHONY : doit_all.i

# target to preprocess a source file
doit_all.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/doit_all.cpp.i
.PHONY : doit_all.cpp.i

doit_all.s: doit_all.cpp.s

.PHONY : doit_all.s

# target to generate assembly for a file
doit_all.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/doit_all.cpp.s
.PHONY : doit_all.cpp.s

fonts/font_tahoma_8pt.o: fonts/font_tahoma_8pt.cpp.o

.PHONY : fonts/font_tahoma_8pt.o

# target to build an object file
fonts/font_tahoma_8pt.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/fonts/font_tahoma_8pt.cpp.o
.PHONY : fonts/font_tahoma_8pt.cpp.o

fonts/font_tahoma_8pt.i: fonts/font_tahoma_8pt.cpp.i

.PHONY : fonts/font_tahoma_8pt.i

# target to preprocess a source file
fonts/font_tahoma_8pt.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/fonts/font_tahoma_8pt.cpp.i
.PHONY : fonts/font_tahoma_8pt.cpp.i

fonts/font_tahoma_8pt.s: fonts/font_tahoma_8pt.cpp.s

.PHONY : fonts/font_tahoma_8pt.s

# target to generate assembly for a file
fonts/font_tahoma_8pt.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/fonts/font_tahoma_8pt.cpp.s
.PHONY : fonts/font_tahoma_8pt.cpp.s

fxprocessor.o: fxprocessor.cpp.o

.PHONY : fxprocessor.o

# target to build an object file
fxprocessor.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/fxprocessor.cpp.o
.PHONY : fxprocessor.cpp.o

fxprocessor.i: fxprocessor.cpp.i

.PHONY : fxprocessor.i

# target to preprocess a source file
fxprocessor.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/fxprocessor.cpp.i
.PHONY : fxprocessor.cpp.i

fxprocessor.s: fxprocessor.cpp.s

.PHONY : fxprocessor.s

# target to generate assembly for a file
fxprocessor.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/fxprocessor.cpp.s
.PHONY : fxprocessor.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/main.cpp.s
.PHONY : main.cpp.s

mls.o: mls.cpp.o

.PHONY : mls.o

# target to build an object file
mls.cpp.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/mls.cpp.o
.PHONY : mls.cpp.o

mls.i: mls.cpp.i

.PHONY : mls.i

# target to preprocess a source file
mls.cpp.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/mls.cpp.i
.PHONY : mls.cpp.i

mls.s: mls.cpp.s

.PHONY : mls.s

# target to generate assembly for a file
mls.cpp.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/mls.cpp.s
.PHONY : mls.cpp.s

wavpack/bits.o: wavpack/bits.c.o

.PHONY : wavpack/bits.o

# target to build an object file
wavpack/bits.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/bits.c.o
.PHONY : wavpack/bits.c.o

wavpack/bits.i: wavpack/bits.c.i

.PHONY : wavpack/bits.i

# target to preprocess a source file
wavpack/bits.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/bits.c.i
.PHONY : wavpack/bits.c.i

wavpack/bits.s: wavpack/bits.c.s

.PHONY : wavpack/bits.s

# target to generate assembly for a file
wavpack/bits.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/bits.c.s
.PHONY : wavpack/bits.c.s

wavpack/extra1.o: wavpack/extra1.c.o

.PHONY : wavpack/extra1.o

# target to build an object file
wavpack/extra1.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/extra1.c.o
.PHONY : wavpack/extra1.c.o

wavpack/extra1.i: wavpack/extra1.c.i

.PHONY : wavpack/extra1.i

# target to preprocess a source file
wavpack/extra1.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/extra1.c.i
.PHONY : wavpack/extra1.c.i

wavpack/extra1.s: wavpack/extra1.c.s

.PHONY : wavpack/extra1.s

# target to generate assembly for a file
wavpack/extra1.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/extra1.c.s
.PHONY : wavpack/extra1.c.s

wavpack/extra2.o: wavpack/extra2.c.o

.PHONY : wavpack/extra2.o

# target to build an object file
wavpack/extra2.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/extra2.c.o
.PHONY : wavpack/extra2.c.o

wavpack/extra2.i: wavpack/extra2.c.i

.PHONY : wavpack/extra2.i

# target to preprocess a source file
wavpack/extra2.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/extra2.c.i
.PHONY : wavpack/extra2.c.i

wavpack/extra2.s: wavpack/extra2.c.s

.PHONY : wavpack/extra2.s

# target to generate assembly for a file
wavpack/extra2.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/extra2.c.s
.PHONY : wavpack/extra2.c.s

wavpack/float.o: wavpack/float.c.o

.PHONY : wavpack/float.o

# target to build an object file
wavpack/float.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/float.c.o
.PHONY : wavpack/float.c.o

wavpack/float.i: wavpack/float.c.i

.PHONY : wavpack/float.i

# target to preprocess a source file
wavpack/float.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/float.c.i
.PHONY : wavpack/float.c.i

wavpack/float.s: wavpack/float.c.s

.PHONY : wavpack/float.s

# target to generate assembly for a file
wavpack/float.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/float.c.s
.PHONY : wavpack/float.c.s

wavpack/metadata.o: wavpack/metadata.c.o

.PHONY : wavpack/metadata.o

# target to build an object file
wavpack/metadata.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/metadata.c.o
.PHONY : wavpack/metadata.c.o

wavpack/metadata.i: wavpack/metadata.c.i

.PHONY : wavpack/metadata.i

# target to preprocess a source file
wavpack/metadata.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/metadata.c.i
.PHONY : wavpack/metadata.c.i

wavpack/metadata.s: wavpack/metadata.c.s

.PHONY : wavpack/metadata.s

# target to generate assembly for a file
wavpack/metadata.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/metadata.c.s
.PHONY : wavpack/metadata.c.s

wavpack/pack.o: wavpack/pack.c.o

.PHONY : wavpack/pack.o

# target to build an object file
wavpack/pack.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/pack.c.o
.PHONY : wavpack/pack.c.o

wavpack/pack.i: wavpack/pack.c.i

.PHONY : wavpack/pack.i

# target to preprocess a source file
wavpack/pack.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/pack.c.i
.PHONY : wavpack/pack.c.i

wavpack/pack.s: wavpack/pack.c.s

.PHONY : wavpack/pack.s

# target to generate assembly for a file
wavpack/pack.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/pack.c.s
.PHONY : wavpack/pack.c.s

wavpack/tags.o: wavpack/tags.c.o

.PHONY : wavpack/tags.o

# target to build an object file
wavpack/tags.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/tags.c.o
.PHONY : wavpack/tags.c.o

wavpack/tags.i: wavpack/tags.c.i

.PHONY : wavpack/tags.i

# target to preprocess a source file
wavpack/tags.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/tags.c.i
.PHONY : wavpack/tags.c.i

wavpack/tags.s: wavpack/tags.c.s

.PHONY : wavpack/tags.s

# target to generate assembly for a file
wavpack/tags.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/tags.c.s
.PHONY : wavpack/tags.c.s

wavpack/unpack.o: wavpack/unpack.c.o

.PHONY : wavpack/unpack.o

# target to build an object file
wavpack/unpack.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/unpack.c.o
.PHONY : wavpack/unpack.c.o

wavpack/unpack.i: wavpack/unpack.c.i

.PHONY : wavpack/unpack.i

# target to preprocess a source file
wavpack/unpack.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/unpack.c.i
.PHONY : wavpack/unpack.c.i

wavpack/unpack.s: wavpack/unpack.c.s

.PHONY : wavpack/unpack.s

# target to generate assembly for a file
wavpack/unpack.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/unpack.c.s
.PHONY : wavpack/unpack.c.s

wavpack/unpack3.o: wavpack/unpack3.c.o

.PHONY : wavpack/unpack3.o

# target to build an object file
wavpack/unpack3.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/unpack3.c.o
.PHONY : wavpack/unpack3.c.o

wavpack/unpack3.i: wavpack/unpack3.c.i

.PHONY : wavpack/unpack3.i

# target to preprocess a source file
wavpack/unpack3.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/unpack3.c.i
.PHONY : wavpack/unpack3.c.i

wavpack/unpack3.s: wavpack/unpack3.c.s

.PHONY : wavpack/unpack3.s

# target to generate assembly for a file
wavpack/unpack3.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/unpack3.c.s
.PHONY : wavpack/unpack3.c.s

wavpack/words.o: wavpack/words.c.o

.PHONY : wavpack/words.o

# target to build an object file
wavpack/words.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/words.c.o
.PHONY : wavpack/words.c.o

wavpack/words.i: wavpack/words.c.i

.PHONY : wavpack/words.i

# target to preprocess a source file
wavpack/words.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/words.c.i
.PHONY : wavpack/words.c.i

wavpack/words.s: wavpack/words.c.s

.PHONY : wavpack/words.s

# target to generate assembly for a file
wavpack/words.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/words.c.s
.PHONY : wavpack/words.c.s

wavpack/wputils.o: wavpack/wputils.c.o

.PHONY : wavpack/wputils.o

# target to build an object file
wavpack/wputils.c.o:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/wputils.c.o
.PHONY : wavpack/wputils.c.o

wavpack/wputils.i: wavpack/wputils.c.i

.PHONY : wavpack/wputils.i

# target to preprocess a source file
wavpack/wputils.c.i:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/wputils.c.i
.PHONY : wavpack/wputils.c.i

wavpack/wputils.s: wavpack/wputils.c.s

.PHONY : wavpack/wputils.s

# target to generate assembly for a file
wavpack/wputils.c.s:
	$(MAKE) -f CMakeFiles/rttmlssa.dir/build.make CMakeFiles/rttmlssa.dir/wavpack/wputils.c.s
.PHONY : wavpack/wputils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rttmlssa"
	@echo "... EasyBMP_1.06/EasyBMP_BMP.o"
	@echo "... EasyBMP_1.06/EasyBMP_BMP.i"
	@echo "... EasyBMP_1.06/EasyBMP_BMP.s"
	@echo "... GBAtext.o"
	@echo "... GBAtext.i"
	@echo "... GBAtext.s"
	@echo "... OS_interface.o"
	@echo "... OS_interface.i"
	@echo "... OS_interface.s"
	@echo "... RTTGDIXCB.o"
	@echo "... RTTGDIXCB.i"
	@echo "... RTTGDIXCB.s"
	@echo "... RTT_2.o"
	@echo "... RTT_2.i"
	@echo "... RTT_2.s"
	@echo "... RTT_button.o"
	@echo "... RTT_button.i"
	@echo "... RTT_button.s"
	@echo "... RTT_colours.o"
	@echo "... RTT_colours.i"
	@echo "... RTT_colours.s"
	@echo "... RTT_generic_decoder.o"
	@echo "... RTT_generic_decoder.i"
	@echo "... RTT_generic_decoder.s"
	@echo "... RTT_keysyms.o"
	@echo "... RTT_keysyms.i"
	@echo "... RTT_keysyms.s"
	@echo "... RTT_pane.o"
	@echo "... RTT_pane.i"
	@echo "... RTT_pane.s"
	@echo "... RTT_patest_wire.o"
	@echo "... RTT_patest_wire.i"
	@echo "... RTT_patest_wire.s"
	@echo "... RTT_player.o"
	@echo "... RTT_player.i"
	@echo "... RTT_player.s"
	@echo "... RTT_text_edit_box.o"
	@echo "... RTT_text_edit_box.i"
	@echo "... RTT_text_edit_box.s"
	@echo "... RTT_vector.o"
	@echo "... RTT_vector.i"
	@echo "... RTT_vector.s"
	@echo "... RTT_wavpack_decoder.o"
	@echo "... RTT_wavpack_decoder.i"
	@echo "... RTT_wavpack_decoder.s"
	@echo "... RTT_window.o"
	@echo "... RTT_window.i"
	@echo "... RTT_window.s"
	@echo "... compressher_limither.o"
	@echo "... compressher_limither.i"
	@echo "... compressher_limither.s"
	@echo "... doit_all.o"
	@echo "... doit_all.i"
	@echo "... doit_all.s"
	@echo "... fonts/font_tahoma_8pt.o"
	@echo "... fonts/font_tahoma_8pt.i"
	@echo "... fonts/font_tahoma_8pt.s"
	@echo "... fxprocessor.o"
	@echo "... fxprocessor.i"
	@echo "... fxprocessor.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mls.o"
	@echo "... mls.i"
	@echo "... mls.s"
	@echo "... wavpack/bits.o"
	@echo "... wavpack/bits.i"
	@echo "... wavpack/bits.s"
	@echo "... wavpack/extra1.o"
	@echo "... wavpack/extra1.i"
	@echo "... wavpack/extra1.s"
	@echo "... wavpack/extra2.o"
	@echo "... wavpack/extra2.i"
	@echo "... wavpack/extra2.s"
	@echo "... wavpack/float.o"
	@echo "... wavpack/float.i"
	@echo "... wavpack/float.s"
	@echo "... wavpack/metadata.o"
	@echo "... wavpack/metadata.i"
	@echo "... wavpack/metadata.s"
	@echo "... wavpack/pack.o"
	@echo "... wavpack/pack.i"
	@echo "... wavpack/pack.s"
	@echo "... wavpack/tags.o"
	@echo "... wavpack/tags.i"
	@echo "... wavpack/tags.s"
	@echo "... wavpack/unpack.o"
	@echo "... wavpack/unpack.i"
	@echo "... wavpack/unpack.s"
	@echo "... wavpack/unpack3.o"
	@echo "... wavpack/unpack3.i"
	@echo "... wavpack/unpack3.s"
	@echo "... wavpack/words.o"
	@echo "... wavpack/words.i"
	@echo "... wavpack/words.s"
	@echo "... wavpack/wputils.o"
	@echo "... wavpack/wputils.i"
	@echo "... wavpack/wputils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

